name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  vmImage: windows-latest

variables:
- group: NuGet
- name: version
  value: 0.1.2
- name: assemblyVersion
  value: 0.0.0.$(Build.BuildId)

jobs:
- job: Build
  steps:
  - powershell: |
      if("$(Build.SourceBranchName)" -ne "main" ) { 
          Write-Host "##vso[task.setvariable variable=version]$(version)-$(Build.SourceBranchName).$(Build.BuildId)" 
      } else {
          Write-Host "##vso[build.updatebuildnumber]$(version)"
      }             
    displayName: 'Configure Version'
  - powershell: |
      .\build.ps1 `
      --SolutionPath=../ `
      --NugetApiKey=$(nuget-key) `
      --BuildVersion=$(version) `
      --AssemblyVersion=$(assemblyVersion)
    displayName: 'Run Cake Script'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: './artifacts/packages'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      searchFolder: './artifacts/test-results/'
      testResultsFiles: '*.trx'